Add example extension for 3rd party package installation
shoutem/extension-examples pull request #3
Opened 2017-05-19 12:32 UTC by Vladimir-Vdovic

Adding an example extension that uses react-native-swiper.

This is the result of:
1) Installing a non-native Package

From the "Installing 3rd Party Packages" tutorial.

2017-05-23 13:34 UTC, tenodi commented
Setup eslint and run through your examples. Once there are no errors, tag me to check it out again.

2017-05-29 14:27 UTC, Vladimir-Vdovic commented
@tenodi Ran ESLint as requested.

2017-06-12 17:18 UTC, tenodi commented
Same comment, ignore `.DS_Store` globally.

2017-06-12 17:20 UTC, tenodi commented
Make sure `node_modules` are ignored as well. This can be done on the repo level too. You've submitted `node_modules` in this PR.

2017-06-12 17:51 UTC, tenodi requested changes
This is good! Just a few things to be changed.

2017-06-12 17:51 UTC, tenodi commented on swiper-extension/.eslintignore
> +**/build/*
Use the repo's `.eslintignore`.

2017-06-12 17:51 UTC, tenodi commented on swiper-extension/.eslintrc
> +{
Use the repo's `.eslintrc`.

2017-06-12 17:51 UTC, tenodi commented on swiper-extension/app/package.json
> +  "name": "vladimir-vdovic.swiper-extension",
`tom` or `vlad`.

2017-07-07 09:26 UTC, Vladimir-Vdovic commented
@tenodi
Should be ready for merge.

No .DS_Store files.

No node_modules folder.

ESLint ran.

Requested changes done.

2018-08-20 10:29 UTC, closed without merging